#include<stdio.h>
#include<conio.h>
#include<stdlib.h>

int main()
{
  int a, b, somma, risultato=0;
  printf("QUESTO PROGRAMMA PERMETTE DI FARE LA SOMMA TRA DUE NUMERI:\n");
  printf("Inserisci un numero:");
  scanf("%d", &a);
  printf("inserisci un numero:");
  scanf("%d", &b);
  somma= a + b;
  risultato= somma;
  printf("il risultato e':&d", risultato);

  getch();
  return 0;
}